max.url.length=2048

shortcode.length=6

shortcode.charset=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

default.ttl.minutes=60

cleaner.interval.seconds=60

uuid.store.path=${user.home}/.shortener_uuid

max.clicks.default=0
